/**
 * Created by grace on 17-1-11.
 */
var data=[
    {
        img:'1.jpg',
        caption:'微微一笑很倾城',
        desc:'微微一笑很倾城'
    },
    {
        img:'2.jpg',
        caption:'我的战争',
        desc:'我的战争'
    },
    {
        img:'3.jpg',
        caption:'铁道飞虎',
        desc:'铁道飞虎'
    },
    {
        img:'4.jpg',
        caption:'疯狂动物城',
        desc:'疯狂动物城'
    },
    {
        img:'5.jpg',
        caption:'极限挑战',
        desc:'极限挑战'
    },
    {
        img:'6.jpg',
        caption:'三傻大闹宝莱坞',
        desc:'三傻大闹宝莱坞'
    },
    {
        img:'7.jpg',
        caption:'海底世界',
        desc:'海底世界'
    },
    {
        img:'8.jpg',
        caption:'激战',
        desc:'激战'
    },
    {
        img:'9.jpg',
        caption:'追凶者也',
        desc:'追凶者也'
    },
    {
        img:'10.jpg',
        caption:'钢铁侠3',
        desc:'钢铁侠3'
    },
    {
        img:'11.jpg',
        caption:'生死狙击',
        desc:'生死狙击'
    },
    {
        img:'12.jpg',
        caption:'美人鱼',
        desc:'美人鱼'
    },
    {
        img:'13.jpg',
        caption:'28岁未成年',
        desc:'28岁未成年'
    },
    {
        img:'14.jpg',
        caption:'澳门风云3',
        desc:'澳门风云3'
    },
    {
        img:'15.jpg',
        caption:'谍影重重',
        desc:'谍影重重'
    },
    {
        img:'16.jpg',
        caption:'老炮儿',
        desc:'老炮儿'
    },
    {
        img:'17.jpg',
        caption:'七月与安生',
        desc:'七月与安生'
    },
    {
        img:'18.jpg',
        caption:'风起',
        desc:'风起'
    },
    {
        img:'19.jpg',
        caption:'源代码',
        desc:'源代码'
    },
    {
        img:'20.jpg',
        caption:'盗墓笔记',
        desc:'盗墓笔记'
    }


];
